# Generated by Django 3.1.2 on 2020-10-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameZH', models.CharField(default='NO NAMEZH', max_length=200)),
                ('nameEN', models.CharField(default='NO NAMEEN', max_length=200)),
                ('addressZH', models.CharField(default='NO ADDRESSZH', max_length=200)),
                ('addressEN', models.CharField(default='NO ADDRESSEN', max_length=200)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
            ],
        ),
    ]
